version: '3'
services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      gos_zakaz_parser:
        ipv4_address: 192.168.55.4

  celery_worker:
    build: .
    container_name: celery_worker
    command: celery -A tasks worker --loglevel=INFO
    depends_on:
      - redis
    networks:
      gos_zakaz_parser:
        ipv4_address: 192.168.55.5

networks:
  gos_zakaz_parser:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.55.0/24
          gateway: 192.168.55.1
          